FeedbackForITStudents/Controllers/CauHoiCaNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FeedbackForITStudents.Models;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace FeedbackForITStudents.Controllers
{
    [Authorize]
    public class CauHoiCaNhanController : Controller
    {
        SEP24Team12Entities model = new SEP24Team12Entities();
        [HttpGet]
        public ActionResult Index()
        {
            var userIdentity = User.Identity.GetUserId();
            var allCauhoi = model.CAUHOIDADUYETs.ToList();
            foreach (var item in allCauhoi)
            {
                if(userIdentity == item.MaTKAsp)
                {
                    var cauhoi = model.TRALOIs.Where(c => c.CAUHOIDADUYET.MaTKAsp == userIdentity).ToList();
                    var canhand = cauhoi.OrderByDescending(d => d.MaCTL);
                    ViewBag.Count = cauhoi.Count();
                    return View(canhand);
                }
                else
                {
                    var cauhoi = model.TRALOIs.Where(c => c.CAUHOIDADUYET.MaTKAsp == userIdentity).ToList();
                    ViewBag.Count = cauhoi.Count();
                    return View(cauhoi);
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Like(int id, TRALOI t)
        {
            TRALOI updateTim = model.TRALOIs.FirstOrDefault(u => u.MaCTL == id);
            if (Request["like"] != null)
            {
                updateTim.Luottim++;
            }
            model.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

FeedbackForITStudents/Views/CauHoiCaNhan/Index.cshtml
@model IEnumerable<FeedbackForITStudents.Models.TRALOI>

@{
    ViewBag.Title = "Câu hỏi cá nhân";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<div class="inner-banner">
    <section class="w3l-breadcrumb">
        <div class="container">
            <h1 class="inner-text-title font-weight-bold mb-2">Câu hỏi cá nhân</h1>
        </div>
    </section>
</div>
<section class="w3l-blog-sec pt-5">
    <div class="services-layout py-md-4 py-3">
        <div class="container">
            <div>
                Bạn có @ViewBag.Count câu hỏi đã được trả lời
            </div>
            @foreach (var item in Model)
            {
                using (Html.BeginForm("Index", "CauHoiCaNhan", FormMethod.Get))
                {
                    <div class="col-lg-12 text11-content m-auto" style="padding-top: 20px">
                        <div class="card border-info mb-3 ">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4" style="max-width: 90px;">
                                        <img src="~/assets/images/student.jpg" class="img-fluid rounded-start" alt="placeholder image">
                                    </div>
                                    <div class="col-md-10">
                                        <h5 class="card-title">@item.CAUHOIDADUYET.Noidung</h5>
                                        <figcaption class="blockquote-footer">
                                            @item.CAUHOIDADUYET.Thoigian.ToShortDateString()<strong> by </strong><cite title="Source Title">
                                                @if (item.CAUHOIDADUYET.Andanh == true)
                                                {
                                                    @item.CAUHOIDADUYET.Email
                                                }
                                                else
                                                {
                                                    <label>Ẩn danh</label>
                                                }
                                            </cite>
                                        </figcaption>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9.5 offset-md-2">
                                <div class="">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-4" style="max-width: 90px;">
                                                <img src="~/assets/images/teacher.jpg" class="img-fluid rounded-start" alt="placeholder image">
                                            </div>
                                            <div class="col-md-10">
                                                <h5 class="card-title" style="color:gray">@item.Noidungtraloi</h5>
                                                <figcaption class="blockquote-footer">
                                                    @item.Thoigian.ToShortDateString()<strong> by </strong><cite title="Source Title">
                                                        BCN Khoa
                                                    </cite>
                                                </figcaption>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-5" style="padding-bottom: 10px" id="PartialView">

                                <button id="likea" name="like" type="submit" class="btn btn-outline-danger">
                                    <i class="fa fa-heart" aria-hidden="true"></i>                             <lable style="">@item.Luottim</lable>
                                </button>
                                @*<button name="unlike" type="submit" class="btn btn-danger"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i></button>*@
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>