FeedbackForITStudents/Areas/Admin/Controllers/AdminHomeController.cs
using FeedbackForITStudents.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebCanteen.Areas.Admin.Middleware;

namespace FeedbackForITStudents.Areas.Admin.Controllers
{
    [LoginVerification]
    public class AdminHomeController : Controller
    {
        SEP24Team12Entities model = new SEP24Team12Entities();
        // GET: Admin/Admin
        public ActionResult Index()
        {
            var cauhoi = model.CAUHOIDADUYETs.ToList();
            var chude = model.CHUDEs.ToList();
            var traloi = model.TRALOIs.OrderByDescending(t => t.MaCTL);
            return View(traloi);
        }
        [HttpPost]
        public ActionResult Like(int id, TRALOI t)
        {
            TRALOI updateTim = model.TRALOIs.FirstOrDefault(u => u.MaCTL == id);
            if (Request["like"] != null)
            {
                updateTim.Luottim++;
            }
            model.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FeedbackForITStudents/Areas/Admin/Views/AdminHome/Index.cshtml
@model IEnumerable<FeedbackForITStudents.Models.TRALOI>

@{
    ViewBag.Title = "Trang chủ Admin";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<script src="~/assets/js/jquery-3.3.1.min.js"></script>

<section id="home" class="w3l-banner py-5">
    <div class="banner-image">

    </div>
    <div class="banner-content">
        <div class="container pt-5 pb-md-4">
            <div class="row align-items-center">
                <div class="col-md-6 pt-md-0 pt-4">
                    <h3 class="mb-lg-4 mb-3 title">
                        Feedback For <span class="typed-text"></span><span class="cursor">&nbsp</span>
                    </h3>
                    <p>
                        Khoa Công nghệ Thông tin thành lập vào năm 1995;
                        Năm 2001, Khoa tham gia vào hệ thống đào tạo kỹ sư công nghệ thông tin theo chuẩn Nhật Bản.
                        Từ năm 2008 đến 2018, Khoa triển khai đào tạo ngành Kỹ thuật Phần mềm theo chương trình do Carnegie Mellon University (đại học số 1 của Mỹ về kỹ thuật phần mềm) chuyển giao.
                    </p>
                </div>
                <div class="col-md-6 mt-md-0 mt-4">
                    <img class="img-fluid" src="~/assets/images/bann1.png" alt=" ">
                </div>
            </div>
        </div>
    </div>
</section>

<section class="w3l-blog-sec pt-5">
    <div class="services-layout py-md-4 py-3">
        <div class="container">
            <div class="text-center mb-sm-5 mb-4">
                <h3 class="title-big">Tất cả câu hỏi</h3>
            </div>
            @foreach (var item in Model)
            {
                using (Html.BeginForm("Like", "AdminHome", new { id = item.MaCTL }))
                {
                    <div class="col-lg-12 text11-content m-auto" style="padding-top: 20px">
                        <div class="card border-info mb-3 ">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-4" style="max-width: 90px;">
                                        <img src="~/assets/images/student.jpg" class="img-fluid rounded-start" alt="placeholder image">
                                    </div>
                                    <div class="col-md-10">
                                        <h5 class="card-title">@item.CAUHOIDADUYET.Noidung</h5>
                                        <figcaption class="blockquote-footer">
                                            @item.CAUHOIDADUYET.Thoigian.ToShortDateString()<strong> by </strong><cite title="Source Title">
                                                @if (item.CAUHOIDADUYET.Andanh == false)
                                                {
                                                    @item.CAUHOIDADUYET.Email
                                                }
                                                else
                                                {
                                                    <label>Ẩn danh</label>
                                                }
                                            </cite>
                                        </figcaption>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-9.5 offset-md-2">
                                <div class="">
                                    <div class="card-body">
                                        <div class="row">
                                            <div class="col-md-4" style="max-width: 90px;">
                                                <img src="~/assets/images/teacher.jpg" class="img-fluid rounded-start" alt="placeholder image">
                                            </div>
                                            <div class="col-md-10">
                                                <h5 class="card-title" style="color:gray">@item.Noidungtraloi</h5>
                                                <figcaption class="blockquote-footer">
                                                    @item.Thoigian.ToShortDateString()<strong> by </strong><cite title="Source Title">
                                                        BCN Khoa
                                                    </cite>
                                                </figcaption>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-5" style="padding-bottom: 10px" id="PartialView">

                                <button id="likea" name="like" type="submit" class="btn btn-outline-danger">
                                    <i class="fa fa-heart" aria-hidden="true"></i>                             <lable style="">@item.Luottim</lable>
                                </button>
                                @*<button name="unlike" type="submit" class="btn btn-danger"><i class="fa fa-thumbs-o-down" aria-hidden="true"></i></button>*@
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</section>
@section scripts{
    <script>
        $('#likea').load('/AdminHome/Like');
    }
    </script>
}