FeedbackForITStudents/Areas/Admin/Controllers/DuyetCauHoiController.cs
using FeedbackForITStudents.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using WebCanteen.Areas.Admin.Middleware;

namespace FeedbackForITStudents.Areas.Admin.Controllers
{
    [LoginVerification]
    public class DuyetCauHoiController : Controller
    {
        // GET: Admin/DuyetCauHoi
        SEP24Team12Entities model = new SEP24Team12Entities();
        public ActionResult Index()
        {
            var cauhoi = model.CAUHOIs.ToList();
            return View(cauhoi);
        }
        [HttpPost]
        public ActionResult Browse(int id, CAUHOIDADUYET d)
        {
            if (Request["delete"] != null)
            {

                var cauhoi = model.CAUHOIs.FirstOrDefault(f => f.MaCH == id);
                model.CAUHOIs.Remove(cauhoi);
                model.SaveChanges();
                return RedirectToAction("Index");
            }
            else if (Request["duyet"] != null)
            {
                CAUHOI cauhoi = model.CAUHOIs.Find(id);
                var cauhoid = new CAUHOIDADUYET { Noidung = cauhoi.Noidung, Andanh = cauhoi.Andanh, Thoigian = cauhoi.Thoigian, Email = cauhoi.Email, MaTKAsp = cauhoi.MaTKAsp};
                cauhoid.pin = d.pin;
                cauhoid.Rep = false;
                cauhoid.MaCD = cauhoi.MaCD;
                model.CAUHOIDADUYETs.Add(cauhoid);
                model.CAUHOIs.Remove(cauhoi);
                model.SaveChanges();
                return RedirectToAction("index");
            }
            return View();
        }
    }
}

FeedbackForITStudents/Areas/Admin/Views/DuyetCauHoi/Index.cshtml
@model IEnumerable<FeedbackForITStudents.Models.CAUHOI>

@{
    ViewBag.Title = "Duyệt câu hỏi";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<script src="~/assets/js/jquery-3.3.1.min.js"></script>

<main style="padding-top: 150px">
    <div class="container">
        <div class="col-lg-12">
            <div class="grid">
                <div class="text-center mb-sm-5 mb-4">
                    <h3 class="title-big">Danh sách câu hỏi cần duyệt</h3>
                    <input type="button" value="Quản lý chủ đề" class="btn btn-outline-primary" onclick="location.href='@Url.Action("Index", "ChuDe")'" style="float:right" />
                </div>               
                <div class="item-wrapper" style="padding-top: 20px">
                    <div class="table-responsive">
                        <table class="table" id="cauhoi-table">
                            <thead class="thead-light">
                                <tr>
                                    <th>
                                        Nội dung câu hỏi
                                    </th>
                                    @*<th>
            Html.DisplayNameFor(model => model.Andanh)
        </th>*@
                                    <th>
                                        Thời gian
                                    </th>
                                    <th>
                                        Tài khoản SV
                                    </th>
                                    @*<th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>*@
                                    <th>
                                        Chủ đề
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    using (Html.BeginForm("Browse", "DuyetCauHoi", new { id = item.MaCH }))
                                    {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Noidung)
                                    </td>
                                    @*<td>
            @Html.DisplayFor(modelItem => item.Andanh)
        </td>*@
                                    <td>
                                        @item.Thoigian.ToString("dd/MM/yyyy")
                                        @*@Html.DisplayFor(modelItem => item.Thoigian)*@

                                    </td>
                                    <td>
                                        @if (item.Andanh == false)
                                        {
                                            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
                                        }
                                        else
                                        {
                                            <label>Ẩn danh</label>
                                        }
                                    </td>
                                    <td >
                                        @Html.DisplayFor(modelItem => item.CHUDE.TenCD)
                                    </td>
                                    <td class="col-lg-3">

                                        <div class="btn-group" data-toggle="buttons">
                                            <label class="btn btn-outline-primary">
                                                <input name="pin" type="checkbox" value="true" />
                                                <input type="hidden" value="false" name="pin" />
                                                <span class="fa fa-thumb-tack"></span>
                                            </label>
                                        </div>
                                        <input type="submit" value="Xóa" class="btn btn-primary" name="delete"
                                               onclick="return confirm('Bạn có chắc chắn muốn xóa câu hỏi này?')" />
                                        <input type="submit" value="Duyệt" class="btn btn-outline-info" name="duyet" />


                                    </td>
                                </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</main>
}
<script>
    $(document).on("click", "[type='checkbox']", function (e) {
        if (this.checked) {
            $(this).attr("value", "true");
        } else {
            $(this).attr("value", "false");
        }
    });
</script>